name: My First Workflow
on: [push]

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v5
            - name: List and Read File
              run: |
                echo "My first GH Actions job"
                ls -ltra
                cat README.md
            - name: Generate ASCII Artwork
              run: cowsay -f dragon "Run for cover, I am a Dragon!" >> dragon.txt
